
# NetGuardAI Snort Configuration
ipvar HOME_NET any
ipvar EXTERNAL_NET any

var RULE_PATH /home/mirza/Desktop/NetGuardAI/rules
var SO_RULE_PATH /home/mirza/Desktop/NetGuardAI/rules
var PREPROC_RULE_PATH /home/mirza/Desktop/NetGuardAI/rules

var HTTP_PORTS 80
var SHELLCODE_PORTS 80
var ORACLE_PORTS 1521

preprocessor frag3_global: max_frags 65536
preprocessor frag3_engine: policy first detect_anomalies

preprocessor stream5_global: max_tcp 8192, track_tcp yes, track_udp yes
preprocessor stream5_tcp: policy first, ports client 21 22 23 25 42 53 80 110 111 135 136 137 138 139 143 161 445 513 514 587 646 691 1433 1521 3306 3389 5556 6660 6661 6662 6663 6664 6665 6666 6667 6668 6669 7000 7001 8000 8080 8180 8443

preprocessor http_inspect: global

preprocessor http_inspect_server: server default \
    http_methods GET POST PUT DELETE HEAD OPTIONS \
    ports { 80 443 } \
    server_flow_depth 0 client_flow_depth 0

output alert_fast: /home/mirza/Desktop/NetGuardAI/logs/snort_alerts.json

logdir /home/mirza/Desktop/NetGuardAI/logs
